config/routes.rb
Rails.application.routes.draw do

resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create, :destroy]

root 'pages#index'
get 'trail_calculator' => 'pages#trail_calculator'
get 'welcome' => 'pages#index'
post 'contact_us' => 'pages#contact_save'
get 'contact_us' => 'pages#contact_us'
get 'about_us' => 'pages#about_us'
get 'business' => 'pages#business'
get 'test' => 'businesses#test'
#get 'signup' => 'pages#signup'

resources :businesses

resources :favourites
get 'offleash_toronto' => 'pages#offleash_toronto'

get '/sign_up', to: 'users#new', as: :sign_up
get '/log_in', to: 'sessions#new', as: :log_in
get '/log_out', to: 'sessions#destroy', as: :log_out

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  max_paginates_per 10
  geocoded_by :business_address
  after_validation :geocode, if: :business_address_changed?
  belongs_to :category
  belongs_to :city

def display_distance_to(other_business_address)
 business_address.distance_to(@business_address, :km).round(3)
end

<<<<<<< HEAD
def nearby_businesses
  if self.geocoded?
    return self.nearbys(5)
  else
    return nil
  end
end
=======
#if business.geocoded?
#  business.nearbys(5)


>>>>>>> master

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :businesses
  belongs_to :cities
end

app/models/city.rb
class City < ApplicationRecord
  has_many :categories
  has_many :businesses
end

app/models/contactus.rb
class Contactus < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/park.rb
class Park < ApplicationRecord
 has_attached_file :photo, default_url: "/images/missing.png"
 validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/session.rb
class Session < ApplicationRecord
  authenticates_with_sorcery!
end

app/models/user.rb
class User < ApplicationRecord

  authenticates_with_sorcery!

  has_many :businesses, through: :favourites
  has_many :favourites


  # validates :password, length: { minimum: 8 }
  # validates :password, confirmation: true
  # validates :email, uniqueness: true, email_format: { message: 'Not a valid email.' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
   if params[:search_address]
    #  @business = Business.all
     @business = Business.near(params[:search_address])
    #  @business2 = Business.near(params[:search_address]).page(params[:page]).per(10)
     @business2 = Business.near(params[:search_address]).page(params[:page]).per(10)
   else

     @business = Business.all
     @business = Business.order("business_name").page(params[:page]).per(10)
    # raise "hell"
   end
 end
  end

  def test
    @user = User.new
  end

  def contact_us
  end

  def business_params
    params.require(:business).permit(:category_id, :business_name, :business_address, :city_id, :latitude, :longitude)
  end

  def business
  end

  def signup

  end

  def show
  end

  def new

    @businesses = Business.new
  end

  def create
    @business = Business.new(business_params)

    if @business.save
      redirect_to root_path
    else
      render :new
    end
  end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

def new
  @favourite = Favourite.new
  redirect_to create
end
  def create

    @favourite = Favourite.new(favourites_params)
    if @favourite.save
       
    puts "***********************"
    puts params[:user_id]
    puts params[:business_id]
    else
    flash.now[:alert] = 'failure to favourite'
    puts "failed to save"

  end
end

def update
    puts "***********************"
puts "you have begun the update prodess"
end

def favourites_params
  puts params.inspect
  puts "----------------------------------------------------------------------------------------------------------"
  params.permit(:user_id, :business_id)
end

def destroy
  Favourite.find_by(id: params[:id]).destroy
  flash[:success] = "Favourite deleted"
  redirect_to businesses_path
  puts "YOU JUST DELETED A FAVOURITE!!!!!!!!!!!!!!!!!!!!!!"

end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

  def contact_us
    @contactus = Contactus.new
  end

  #def contact_save
  #  @contactus = Contactus.new(contact_params)
  #  if @contactus.save
  #    redirect_to contact_us_url
  #  else
  #    render :contact_us
  #  end
  #end

def contact_save
  @contactus = Contactus.new(contact_params)
   if @contactus.save
    AdminMailer.business_details(@contactus).deliver_later
    SubmissionMailer.received(@contactus).deliver_later
    redirect_to contact_us_url
    else
      render :contact_us
    end
end

  def business
  end

  def signup
  end

  def show
  end

  private
  def contact_params
    params.permit(:firstname, :lastname, :email, :businessaddress, :businessname, :businessowner, :message)
  end

  def offleash_toronto
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def create
  @park = Park.create(park_params )
end

  def index
    @parks = Park.all
    
  end

  def new
    @park = Park.new
  end



private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def park_params
  params.require(:park).permit(:photo, :name, :description)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # venue = Venue.authenticate(params[:email], params[:password])
    # origionally in create
    # band = Band.authenticate(params[:email], params[:password])
    # if band
    #   session[:band_id] = band.id
    #   redirect_to root_url, :notice => "Logged in!"
    # else
    #   flash.now.alert = "Invalid email or password"
    #   render "new"
    # end

    user = User.authenticate(params[:email], params[:password])
    # raise 'hell'
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
      puts"**********************SUCCESS"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
        puts"**********************FAIL"
    end


  end


    def destroy
      session[:user_id] = nil
      redirect_to root_url, :notice => "Logged out!"
    end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
        redirect_to root_path, alert: "signed up"
        puts "*****USER CREATED"
      else
      flash.now[:alert] = 'failure'
      puts "*******fialure"
        render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def pageid
    "#{params[:controller]}-#{params[:action]}"
  end

end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/business/show.html.erb
<div class="centered">

<h1><%= @business_find.business_name %></h1>
Address: <%= @business_find.business_address %><br>
city: <%=  @business_find.city.city_name %>

</div>

app/views/businesses/index.html.erb
<div class="form_text">



  <h1 class="center "> List of Businesses </h1>

  <br>
  <br>

<h2>Find nearby Businesses!</h2>
<%= form_tag businesses_path, method: :get do %>
   <%= text_field_tag :search_address, params[:search_address] %>
   <%= submit_tag "Find!", class: "brown_background" %>
<% end %>


  <div class="centered">


  <% @business.each do |business| %>


   <div class=" ">
    <table class="business_list">
      <tr>
        <td class="row1 ">
          Business Name
        </td>
        <td class="row2 ">
          <%= business.business_name %>
        </td>

      <% if current_user %>
          <% if Favourite.where(user_id: current_user, business_id: business.id).last != nil%>
          <% getrid = Favourite.where(user_id: current_user, business_id: business.id).last.id %>
          <% end %>

            <% if Favourite.where(user_id: current_user, business_id: business.id).last == ''%>
            <td  rowspan="3" data-to-delete= '<%= getrid %>'  data-user= "<%=current_user.id %>" data-bus= "<%= business.id%>" class="empty_heart">

            <% elsif Favourite.where(user_id: current_user, business_id: business.id).last == nil%>
            <td rowspan="3" data-to-delete= ''  data-user= "<%=current_user.id %>" data-bus= "<%= business.id%>" class="empty_heart">

            <% else %>
            <td rowspan="3" data-to-delete= '<%= getrid %>'  data-user= "<%=current_user.id %>" data-bus= "<%= business.id%>" class="full_heart">
            <%end %>
        <% else %>
      <% end %>

      </td>

      </tr>
    <tr>
      <td class="row1 ">
        Address
      </td>
      <td class="row2 ">
      <%=   business.business_address %>
      </td>
    </tr>

    <tr>
      <td class="row1 ">
        City
      </td>
      <td class="">
      <%#=   business.city.city_name %> Toronto
      </td>
    </tr>




    <tr>
      <td rowspan= '3'>

<br>
  <%= link_to 'View', business.url,  :target => "_blank", class: 'button' %>

      </td>
    </tr>
  <br>
    </table>
  <br>
  <br>

   </div>
  <% end %>

  </div>

  <% if @business == Business.order("business_name").page(params[:page]).per(10) %>
  <%= paginate @business%>
  <% else %>
    <%= paginate @business2%>

  <% end %>
</div>

app/views/businesses/new.html.erb
<div class="centered">

<h2>Add business</h2>
<h4>Fill in the fields below to add your restruant</h4>


<%@business = Business.new %>
<%= form_for @businesses do |f| %>
  <br>
  <% if @business.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

    <ul>
    <% @business.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<table style="width:50%">

  <tr>
    <td><%= f.label :business_name %></td>
    <td><%= f.text_field :business_name %></td>
  </tr>
  <tr>
    <td><%= f.label :business_address %></td>
    <td><%= f.text_field :business_address%></td>
  </tr>

</table>
<br>

<%= f.submit %>
</p>

<% end %>


</div>

app/views/businesses/show.html.erb
<div class="centered">

<h1><%= @business_find.business_name %></h1>
Address: <%= @business_find.business_address %><br>
city: <%= @business_find.city.city_name %>

</div>

app/views/businesses/test.html.erb
<body class="sign-up">
  <div class="sign-up-form">

    <h3>Sign Up Today!</h3>
    <br>

    <body class="image">

    <%= form_for @user do |f| %>

      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
      </div> <br>

      <div class="field">
        <%= f.label :email %> <br>
        <%= f.text_field :email %>
      </div> <br>
      <div class="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password %>
      </div><br>
      <div class="field">
        <%= f.label :password_confirmation, "Confirm Password"%>
        <%= f.password_field :password_confirmation %>
      </div><br>

      <div class="actions">
        <%= f.submit 'Create User', :class => 'submitting'%>
        <% end %>

      </div>

    </body>
  </div>
  <img class="arrow"></img>

</body>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bestfriendly</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all'%>
      <%= javascript_include_tag 'application' %>

  </head>



<% flash.each do |name, msg| %>
<div class="centered yellow">
<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>

    <body>



<div class="nav_top">

  <div class="">
    <ul>
      <li class = 'nav hover'><%= link_to "Home", "/" %></li>
      <li class='nav hover'><%= link_to "About Us", about_us_path %> </li>
      <li class = 'nav hover'><%= link_to "Contact Us", contact_us_path, id:"contact-link" %></li>
      </ul>
  </div>
  <div class="upper_right">
  <%= image_tag('t', class: 'small_logo ')  %> <%= image_tag('g', class: 'small_logo')  %><%= image_tag('fb',  class: 'small_logo')  %>
  </div>
</div>
<div class="center">
<%=image_tag"logo2.png", class:"logoimage" %>
  <div class="nav_top">
    <nav>
      <ul>
        <li class = 'nav hover'><%= link_to "Map", "/" %></li>
        <li class = 'nav hover'><%= link_to "Business List", businesses_path%></li>
       <li class='nav hover'><%= link_to "Offleash Toronto", offleash_toronto_path %></li>
       <li class='nav hover'><%= link_to "Trail Calculator", trail_calculator_path %></li>
        <% if current_user %>
            <li class='nav hover'><span class="c_gold">Logged in as: <%= current_user.name %></span></li>
            <li class='nav hover'><%= link_to 'Log Out', log_out_path %></li>
            <% else %>
            <li class='nav hover'>  <%= link_to "Sign up", sign_up_path %> </li>
            <li class='nav hover'>  <%= link_to "Log in", log_in_path %></li>
            <% end %>
        </ul>
    </nav>
</div>










<!--
      <div class="line">
        <div class="hover brown_background v overflow">
          <div class="bottom_bar">
            <div class="nav_top">
              <ul>
                <li class = 'nav'><%= link_to "Home", "/" %></li>
                <li class='nav'><%= link_to "About Us", about_us_path %> </li>
                <li class = 'nav'><%= link_to "Contact Us", "contact_us", id:"contact-link" %></li>
                </ul>
            </div>
            <div class="logo">
              <a href="index.html"><%=image_tag"logo2.png", class:"logoimage" %></a>
              <p class="slogan">Built for dog owners by dog owners</p>
            </div>
          </div>
        </div> -->



      <!-- <div class="brown_background">
        <div class="bottom_bar">
            <div class="nav_top">
              <ul>
                <li class = 'nav'><%= link_to "Home", "/" %></li>
                <li class='nav'><%= link_to "About Us", about_us_path %> </li>
                <li class = 'nav'><%= link_to "Contact Us", "contact_us", id:"contact-link" %></li>
                </ul>
            </div>
            <div class="logo">
              <a href="index.html"><%=image_tag"logo2.png", class:"logoimage" %></a>
              <p class="slogan">Built for dog owners by dog owners</p>
            </div>
            <nav>
              <ul>
                <li class = 'nav'><%= link_to "Home", "/" %></li>
                <li class = 'nav'><%= link_to "Business", businesses_path%></li>
                <li class = 'nav'><%= link_to "Contact Us", "contact_us", id:"contact-link" %></li>
                <li class='nav'><%= link_to "About Us", about_us_path %> </li>
               <li class='nav'><%= link_to "Offleash Toronto", offleash_toronto_path %></li>
                <% if current_user %>
                    <li class='nav'><span>Logged in as: <%= current_user.name %></span></li>
                    <li class='nav'><%= link_to 'Log Out', log_out_path %></li>
                    <% else %>
                    <li class='nav'>  <%= link_to "Sign up", sign_up_path %> </li>
                    <li class='nav'>  <%= link_to "Log in", log_in_path %></li>
                    <% end %>

                </ul>
            </nav>
        </div>
      </div>
  </div> -->

        <div class="modal">
            <form class="contactus" action="/contact-us" method="post">
                <button type="button" class="close">x</button>
                <p>
                  <%= hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %>
                </p>
                <input type="text" id="first" name="FirstName" placeholder="FirstName">
                <input type="text" id="last" name="LastName" placeholder="LastName">
                <input type="text" id="email" name="E-Mail" placeholder="E-Mail">
                <input type="text" id="bname" name="BusinessName" placeholder="BusinessName">
                <input type="text" id="baddress" name="BusinessAddress" placeholder="BusinessAddress">
                <input type="textarea" id="message" name="Message" placeholder="Message">
                <input type="submit" class="submit"/>
            </form>
        </div>

        <div class="signinsignup">
  <div class="regsignin">
    <form class="signinform">
        <button type="button" class="close">x</button>
        <input type="text" name="user" placeholder="Username">
        <input type="password" name="pass" placeholder="Password">
        <button type="button" class="signinsubmit">Submit</button>
    </form>
  </div>

<p class="bfmain">New to Best Friendly? Register Now</p>

<div class="fbsigin">
  <p> Log in with Twitter account </p>
  <form class="fbform">
    <input type="text" name="user" placeholder="Username">
      <input type="password" name="pass" placeholder="Password">
      <button type="button" class="fbsubmit">Submit</button>
  </form>
</div>

</div>
    <%= yield %>
  </body>
  </html>

app/views/pages/about_us.html.erb
<div class="form_text">




  <h1 class=""> Built By Dog Owners For Dog Owners </h1>

  <article class="">
    Welcome to best friendly, a web application that was created because this dog owner saw a problem
    and has created a solution! I love my dog and I want to bring him with me everywhere I go,
    but I don’t always know which businesses want to welcome myself and my pup into their establishments.
  <p>
    Therefore, this simple application shows all the dog friendly businesses within your immediate vicinity
    and allows you to find a specific type of business by category, name or location!
    We also want to know if you have a favourite dog friendly business that you and your pup enjoy.
    We will add them to our list and offer said business the chance to grab a sticker to smack in their window
    so we, who love dogs, can identify best friendly businesses while out and about in our adventures.
  </p>
    From Toronto and own a dog friendly business? SUBMIT YOUR BUSINESS!
    I’ll come for a visit, meet the management and offer a sticker for your window.
    From another city? SUBMIT YOUR BUSINESS! We'll send you a sticker!
  <p>
    Want to advertise with us? Just ask! We only accept ads from pet friendly businesses,
    however we will happily design your ad to your specifications for a small fee.
    Otherwise, just enjoy! Take a poke around the neighbourhood and find out where your favourite furry friends are welcome.
  </p>
  Thanks!
  <p>
  Allie Bell
  Founder of Best Friendly.
  </p>
  </article>
</div>

app/views/pages/contact_us.html.erb
<div class="sign-up-form">

<h1> Contact Us </h1>

<%= form_tag "/contact_us" do %>
  <p>
    <%= hidden_field_tag request_forgery_protection_token.to_s, form_authenticity_token %>
  </p>
  <p>
    <%= label_tag :firstname %><br>
    <%= text_field_tag :firstname %>
  </p>
  <p>
    <%= label_tag :lastname %><br>
    <%= text_field_tag :lastname %>
  </p>
  <p>
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label_tag :businessname %><br>
    <%= text_field_tag :businessname %>
  </p>

  <p>
    <%= label_tag :businessaddress %><br>
    <%= text_field_tag :businessaddress %>
  </p>

  <p>
    <%= label_tag :businessowner %><br>
    <%= check_box_tag :businessowner %>
  </p>

  <p>
    <%= label_tag :message %><br>
    <%= text_field_tag :message %>
  </p>

  <p>
    <%= submit_tag "Save", class: "brown_background" %>
  </p>
<% end %>
</div>

app/views/pages/index.html.erb
   <div class = "centered" id="map"></div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

   <script>
     function initMap() {
       var map = new google.maps.Map(document.getElementById('map'), {
         center: {lat: -43.653, lng: 79.383},
         zoom: 14
       });
       var infoWindow = new google.maps.InfoWindow({map: map});
       function createMarker (lat, lng, title, content, url) {
         var myLatLng = {lat: lat, lng: lng };
         var contentString = '<div id="content">'+
         '<div id="siteNotice">'+
         '</div>'+
         '<h1 id="firstHeading" class="firstHeading">'+
         title +
         '</h1>'+
         '<div id="bodyContent">'+
         '<p>'+
         content +
         '</p>'+
         '<p>'+
          '<a href ="' + url + '">' + url + ' </a> ' +
         '</P>' +
         '</div>'+
         '</div>';


        //  <a href="slkdjfsdfkj">sss</a>


         var infowindow = new google.maps.InfoWindow({
           content: contentString
         });
         //
         var marker = new google.maps.Marker({
           position: myLatLng,
           map: map,
         });
         marker.addListener('click', function() {
           infowindow.open(map, marker);
         });
       }
       // Try HTML5 geolocation.
       if (navigator.geolocation) {
         navigator.geolocation.getCurrentPosition(function(position) {
           var pos = {
             lat: position.coords.latitude,
             lng: position.coords.longitude
           };
           infoWindow.setPosition(pos);
           infoWindow.setContent('You and your dog are here!');
           map.setCenter(pos);
      <% Business.all.each do |business| %>
          createMarker(<%=business.latitude%> , <%=business.longitude%> , '<%=business.business_name%>' , '<%=business.business_address%>' , '<%=business.url%>');

     <% end %>
         }, function() {
           handleLocationError(true, infoWindow, map.getCenter());
         });
       } else {
         // Browser doesn't support Geolocation
         handleLocationError(false, infoWindow, map.getCenter());
       }
     }
     function handleLocationError(browserHasGeolocation, infoWindow, pos) {
       infoWindow.setPosition(pos);
       infoWindow.setContent(browserHasGeolocation ?
                             'Error: The Geolocation service failed.' :
                             'Error: Your browser doesn\'t support geolocation.');
     }
   </script>
   <%# raise Rails.application.secrets.google_maps_api_key %>
   <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.secrets.google_maps_api_key %>&callback=initMap">
     <%= puts "My key --->#{Rails.application.secrets.google_maps_api_key}<---" %>
     </script>

app/views/pages/signup.html.erb
<h1> Sign up </h1>

app/views/pages/trail_calculator.html.erb
<div class="form_text">


<div>
  <h1>Trail Length Calculator:</h1>
</div>
<br>

<div class="my_table_center">
<table id="myTable" class="order-list">
        <tr>
            <td id = 'first_box' class = ''></td>
            <td class = 'name'> Unit Length (km) </td>
            <td class = 'name'># of times Unit Length Fits Into Object</td>
        </tr>
        <tr>
            <td class = 'name measurement'>Measurement 1   </td>
            <td>  <input id = "a0" class = 'text_box' type="text" name="name" value ="160" /></td>
            <td>  <input id = "b0" class = 'text_box' type="text" name="price" value ="20" />  </td>
            <td class = 'name'>Fractal Dimension</td>
            <td><a class="deleteRow"></a></td>
        </tr>
        <tr>
          <td class = 'name measurement'>Measurement 2   </td>
          <td>  <input id = "a1" class = 'text_box' type="text" name="name" value ="80"  />  </td>
          <td>  <input id = "b1" class = 'text_box' type="text" name="price" value ="47"  />    </td>
          <td>  <input id = "fdbox0" disabled="disabled" class = 'text_box calc_text' type="text"  />    </td>
        </tr>
    <tfoot>
        <tr>
            <td colspan="5" style="text-align: left;">
                <input type="button" id="addrow" class = "brown_background" value="Add Row" />
            </td>
        </tr>

    </tfoot>
</table>
<br>
<br>
</div>
<div class="my_table_center">


  <table class="centered">
    <tr>
      <td class = 'name2'> Ant Scale</td>
      <td class = 'name2'> Dog Scale</td>
      <td class = 'name2'> Human Scale</td>
      <td class = 'name2'> Custom Scale</td>
      <td class = 'name2'>Calc Custom Scale</td>
      <td class = 'name2'>Total Length</td>
    </tr>
    <tr>
      <td>  <button id = 'calculate_perimeter_ant' class = "button2 " type="button"  >Calculate</button>  </td>
      <td>  <button id = 'calculate_perimeter_dog' class = "button2 " type="button"  >Calculate</button>  </td>
      <td>  <button id = 'calculate_perimeter_human' class = "button2 " type="button"  >Calculate</button>  </td>        <td>  <input id = "scale" class = 'scale_box' type="text" name="price" value = 80 /></td>
      <td>  <button id = 'calculate_perimeter' class = "button2" type="button"  >Calculate</button>  </td>
      <td>  <input id = "perimeter" class = 'text_box2' type="text" name="price"  />    </td>
    </tr>
  </table>

</div>




<br>
<br>

<h3>Guide:</h3>   <br>
<div class="align_left">
This calculator can be used to calculate distances for natural objects at any scale. The length of any fractal like natural objects depends upon the scale at which you measure them. Examples include: coastlines, trails, the perimeter of a pond, lake or island. Etc.
<br><br>

  Step 1: Measure your trail/pond/coastline using different unit lengths (ex. 1km and 2km lengths)
  <br><br>
  Step 2: Record the numbe of times each unit length fits into each trail/pond/coastline.
  <br><br>
  Step 3: Input values from step 1 and 2, choose a scale, and press calculate

<br><br><br>
<div class="centered">


  Example: The following are values from the coastline of britain obtained from rspatial.org:
</div>
<br>
<br>

<div class="centered">


  <table class ="example">
    <tr>
      <td>  Unit Length  </td>
      <td>    # times fits into object  </td>
    </tr>
    <tr>
      <td> 250  </td>
      <td> 10   </td>
    </tr>
    <tr>
      <td> 200  </td>
      <td> 13   </td>
    </tr>
    <tr>
      <td> 150  </td>
      <td> 18   </td>
    </tr>
    <tr>
      <td> 100  </td>
      <td> 29   </td>
    </tr>
    <tr>
      <td> 50  </td>
      <td> 72   </td>
    </tr>
    <tr>
      <td> 25  </td>
      <td> 169   </td>
    </tr>
  </table>
</div>

<br><br>

<div class="centered">
  <%= image_tag('britain.png', class: 'britain')  %>

</div>




</div>



<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/parks/index.html.erb
<% @parks.each do |park| %>
  pic <br>

<%= image_tag park.photo.url, class: 'hand' %>
<% end %>

app/views/parks/new.html.erb
<div class="centered">

<h2>Add park</h2>

<%= form_for @park, url: parks_path, html: { multipart: true } do |f| %>
<br>
<% if @park.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@park.errors.count, "error") %> prohibited this park from being saved:</h2>

  <ul>
  <% @park.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<table style="width:50%">

<tr>
  <td><%= f.label :name %></td>
  <td><%= f.text_field :name %></td>
</tr>
<tr>
  <td><%= f.label :description %></td>
  <td><%= f.text_field :description %></td>
</tr>

<tr>
  <td><%= f.label :photo %></td>
  <td><%= f.file_field :photo %></td>
</tr>


</table>
<br>

<%= f.submit %>
</p>

<% end %>


</div>

app/views/users/new.html.erb
  <div class="sign-up-form">

    <h3>Sign Up Today!</h3>
    <br>

    <body class="image">

    <%= form_for @user do |f| %>

      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %> <br>
        <%= f.text_field :name %>
      </div> <br>

      <div class="field">
        <%= f.label :email %> <br>
        <%= f.text_field :email %>
      </div> <br>
      <div class="field">
        <%= f.label :password %> <br>
        <%= f.password_field :password %>
      </div><br>
      <div class="field">
        <%= f.label :password_confirmation, "Confirm Password"%>
        <%= f.password_field :password_confirmation %>
      </div><br>

      <div class="actions">
        <%= f.submit 'Create User', :class => 'submitting'%>
        <% end %>

      </div>

    </body>
  </div>
  <img class="arrow"></img>